tasks:
  - name: gitpod
    before: |
      cd ../gitpod
    init: |
      chmod +x install.sh
    command: |
      ./install.sh
      rclone config file
      curl $RCLONE_CONFIG_URL -o /home/gitpod/.config/rclone/rclone.conf
      rclone config

checkoutLocation: /thx

vscode:
  extensions:
    - PKief.material-icon-theme
    - zhuangtongfa.material-theme
    - esbenp.prettier-vscode
    - ms-python.python
    - bradlc.vscode-tailwindcss
