tasks:
  - name: gitpod
    before: |
          cd ../gitpod
    init: |
      chmod +x install.sh
    command: |
      ./install.sh

vscode:
  extensions:
    - PKief.material-icon-theme
    - zhuangtongfa.material-theme
    - esbenp.prettier-vscode
    - ms-python.python
    - bradlc.vscode-tailwindcss
